### ISSUE TITLE
Uniapp 中的 深度选择器 deep-selectors 使用

### ISSUE THREAD

**Issue by sumaolin** [sumaolin/sumaolin.github.io#3]
看视频教程时候，提到覆盖 uni-ui 组件的颜色的时候用到了：

```scss
:deep(){
	color:$brand-theme-color !important;
}
```

看到弹幕提到看Vue的文档：[单文件组件 CSS 功能 | Vue.js](https://cn.vuejs.org/api/sfc-css-features.html#deep-selectors)  中的 深度选择器 deep-selectors
